export const staticcontent = {
    Species:
    [
        {Species: "Brook Trout", Id: "BKT"},
        {Species: "Brown Trout", Id: "BNT"},
        {Species: "Burbot", Id: "BUB"},
        {Species: "Bowfin (dogfish)", Id: "BOF"},
        {Species: "Black Crappie", Id: "BLC"},
        {Species: "Bluegill", Id: "BLG"},
        {Species: "Bluntnose Minnow", Id: "BNM"},
        {Species: "Brown Bullhead", Id: "BRB"},
        {Species: "Channel Catfish", Id: "CCF"},
        {Species: "Chinook Salmon", Id: "CHS"},
        {Species: "Common Carp", Id: "CAP"},
        {Species: "Golden Shiner", Id: "GOS"},
        {Species: "Lake Sturgeon", Id: "LKS"},
        {Species: "Lake Trout", Id: "LAT"},
        {Species: "Lake Whitefish", Id: "LKW"},
        {Species: "Largemouth Bass", Id: "LMB"},
        {Species: "Logperch", Id: "LGP"},
        {Species: "Mottled Sculpin", Id: "MTS"},
        {Species: "Muskellunge", Id: "MUE"},
        {Species: "Northern Pike", Id: "NOP"},
        {Species: "Pumpkinseed", Id: "PMK"},
        {Species: "Rock Bass", Id: "RKB"},
        {Species: "Smallmouth Bass", Id: "SMB"},
        {Species: "Splake", Id: "SPT"},
        {Species: "Spottail Shiner", Id: "SPO"},
        {Species: "Sunfish", Id: "PNK"},
        {Species: "Tiger Muskellunge", Id: "TME"},
        {Species: "Tulibee", Id: "TLC"},
        {Species: "Walleye", Id: "WAE"},
        {Species: "White Bass", Id: "WHB"},
        {Species: "White Sucker", Id: "WTS"},
        {Species: "Yellow Bullhead", Id: "YEB"},
        {Species: "Yellow Perch", Id: "YEP"},
    ],

    counties:
    [
        {County: "Aitkin", Id: 1},
        {County: "Anoka", Id: 2},
        {County: "Becker", Id: 3},
        {County: "Beltrami", Id: 4}, 
        {County: "Benton", Id: 5},
        {County: "Big Stone", Id: 6},
        {County: "Blue Earth", Id: 7},
        {County: "Brown", Id: 8},
        {County: "Carlton", Id: 9},
        {County: "Carver", Id: 10},
        {County: "Cass", Id: 11},
        {County: "Chippewa", Id: 12},
        {County: "Chisago", Id: 13},
        {County: "Clay", Id: 14},
        {County: "Clearwater", Id: 15},
        {County: "Cook", Id: 16},
        {County: "Cottonwood", Id: 17},
        {County: "Crow Wing", Id: 18},
        {County: "Dakota", Id: 19},
        {County: "Dodge", Id: 20},
        {County: "Douglas", Id: 21},
        {County: "Faribault", Id: 22},
        {County: "Fillmore", Id: 23},
        {County: "Freeborn", Id: 24},
        {County: "Goodhue", Id: 25},
        {County: "Grant", Id: 26},
        {County: "Hennepin", Id: 27},
        {County: "Houston", Id: 28},
        {County: "Hubbard", Id: 29},
        {County: "Isanti", Id: 30},
        {County: "Itasca", Id: 31},
        {County: "Jackson", Id: 32},
        {County: "Kanabec", Id: 33},
        {County: "Kandiyohi", Id: 34},
        {County: "Kittson", Id: 35},
        {County: "Koochiching", Id:36},
        {County: "Lac Qui Parle", Id: 37},
        {County: "Lake", Id: 38},
        {County: "Lake of the Woods", Id: 39},
        {County: "Le Suerur", Id: 40},
        {County: "Lincoln", Id: 41},
        {County: "Lyon", Id: 42},
        {County: "Mahnomen", Id: 44},
        {County: "Marshall", Id: 45},
        {County: "Martin", Id: 45},
        {County: "McLeod", Id: 43},
        {County: "Meeker", Id: 47},
        {County: "Mille Lacs", Id: 48},
        {County: "Morrison", Id: 49},
        {County: "Mower", Id: 50},
        {County: "Murray", Id: 51},
        {County: "Nicollet", Id: 52},
        {County: "Nobles", Id: 53},
        {County: "Norman", Id: 54},
        {County: "Olmsted", Id: 55},
        {County: "Otter Tail", Id: 56},
        {County: "Pennington", Id: 57},
        {County: "Pine", Id: 58},
        {County: "Pipestone", Id: 59},
        {County: "Polk", Id: 60},
        {County: "Pope", Id: 61},
        {County: "Ramsey", Id: 62},
        {County: "Red Lake", Id: 63},
        {County: "Redwood", Id: 64},
        {County: "Renville", Id: 65},
        {County: "Rice", Id: 66},
        {County: "Rock", Id: 67},
        {County: "Roseau", Id: 68},
        {County: "Scott", Id: 70},
        {County: "Sherburne", Id: 71},
        {County: "Sibley", Id: 72},
        {County: "Stearns", Id: 73},
        {County: "Steele", Id: 74},
        {County: "Stevens", Id: 75},
        {County: "St. Louis", Id: 69},
        {County: "Swift", Id: 76},
        {County: "Todd", Id: 77},
        {County: "Traverse", Id: 78},
        {County: "Wabasha", Id: 79},
        {County: "Wadena", Id: 80},
        {County: "Waseca", Id: 81},
        {County: "Washington", Id: 82},
        {County: "Watowan", Id: 83},
        {County: "Wilkin", Id: 84},
        {County: "Winona", Id: 85},
        {County: "Wright", Id: 86},
        {County: "Yellow Medicine", Id: 87}
    ]
}